# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jonathan Dobson
# Description of the Site
description: Full Stack Developer and UX Designer
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Web Developer, Full Stack, React, JavaScript, CSS, Linux
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: fromjdobson@gmail.com
facebook_username: fromjon
twitter_username: Jonatha94372804
# instagram_username: /
linkedin_username: fromjon
github_username:  Jonathan-Dobson
youtube_channel_id: UC9jC1tDCjIeRGvITGpnxdMQ
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: G-G6822SSGWD

# Disqus
# disqus-shortname: /

# Name of the Author
author-name: Jonathan Dobson
# URL for the Image of the Author
author-image: /github-pages-example/assets/images/me.jpeg
# 60 Words About the Author
author-about: Web Developer, Full Stack, React, JavaScript, CSS, Linux
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.io/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
